ex1.1:
	go build ex1.1.go
	./ex1.1 aaa bbb
	rm -f ex1.1

ex1.2:
	go run ex1.2.go aaa bbb ccc

ex1.3:
	go run ex1.3.go aaa bbb ccc

ex1.4:
	go run ex1.4.go data/a.txt data/b.txt data/c.txt

ex1.5:
	go run ex1.5.go > assets/ex1.5.gif

ex1.6:
	go run ex1.6.go > assets/ex1.6.gif

ex1.7:
	go run ex1.7.go http://gopl.io

ex1.8:
	go run ex1.8.go gopl.io

ex1.9:
	go run ex1.9.go gopl.io

ex1.10:
	rm -f assets/ex1.10-*
	go run ex1.10.go https://docs.microsoft.com/ja-jp/azure/architecture/best-practices/api-implementation https://docs.github.com/ja/actions/guides/about-continuous-integration
	go run ex1.10.go https://docs.microsoft.com/ja-jp/azure/architecture/best-practices/api-implementation https://docs.github.com/ja/actions/guides/about-continuous-integration
