ex1.1:
	go build ex1.1.go
	./ex1.1 aaa bbb
	rm -f ex1.1

ex1.2:
	go run ex1.2.go aaa bbb ccc

ex1.3:
	go run ex1.3.go aaa bbb ccc

ex1.4:
	go run ex1.4.go data/a.txt data/b.txt data/c.txt

ex1.5:
	go run ex1.5.go > assets/ex1.5.gif

ex1.6:
	go run ex1.6.go > assets/ex1.6.gif
