.PHONY: surface ex3.1 ex3.2 ex3.3

surface:
	go run surface/main.go > assets/surface.svg

ex3.1:
	go run ex3.1/main.go > assets/ex3.1.svg

ex3.2:
	go run ex3.2/main.go -shape="saddle" > assets/ex3.2-saddle.svg
	go run ex3.2/main.go -shape="bump" > assets/ex3.2-bump.svg
	go run ex3.2/main.go -shape="egg pack" > assets/ex3.2-eggpack.svg
ex3.3:
	go run ex3.3/main.go > assets/ex3.3.svg
