.PHONY: sha256 ex4.1 ex4.2 ex4.5 ex4.6 ex4.7 ex4.8 ex4.9 ex4.10 ex4.12 ex4.13 test

test:
	go test -v ./...

sha256:
	go run sha256/main.go

ex4.1:
	go run ex4.1/main.go

ex4.2:
	go run ex4.2/main.go

ex4.5:
	go run ex4.5/main.go

ex4.6:
	go run ex4.6/main.go

ex4.7:
	go run ex4.7/main.go

ex4.8:
	go run ex4.8/main.go < charcount/rashomon.txt

ex4.9:
	go run ex4.9/main.go < ex4.9/machine_learning.txt

ex4.10:
	go run ex4.10/main.go is:open json decoder repo:golang/go

ex4.12:
	go run ex4.12/main.go 571
	go run ex4.12/main.go 571
	go run ex4.12/main.go 572
